### ISSUE TITLE
Server Crash, "Exception ticking world" . . . "because of '$$0' is null"

### ISSUE THREAD

**Issue by Rage-GitHub** [sleepingdragoninn/antique-atlas#165]
This has happened across two modpack instances, with Antique Atlas 4, Surveystones and a Waystones mods. I can't really figure out what is proccing it to crash the server and render a world corrupt, but it can be replicated nonetheless.

I've provided a detailed crash report from the server below.
[crash-2024-07-11_02.33.46-server.txt](https://github.com/user-attachments/files/16172628/crash-2024-07-11_02.33.46-server.txt)
```
Console
02:33:46

net.minecraft.class_148: Exception ticking world
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5321.method_29177()" because "$$0" is null
at net.minecraft.class_2540.method_44116(class_2540.java:737) ~[server-intermediary.jar:?]
at net.minecraft.class_2540.method_34064(class_2540.java:267) ~[server-intermediary.jar:?]
at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
at net.minecraft.class_2540.method_34063(class_2540.java:265) ~[server-intermediary.jar:?]
at folk.sisby.surveyor.packet.S2CStructuresAddedPacket.writeBuf(S2CStructuresAddedPacket.java:67) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.packet.S2CStructuresAddedPacket.toBufs(S2CStructuresAddedPacket.java:81) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:21) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:27) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.PlayerSummary$ServerPlayerEntitySummary$ServerPlayerExploration.addStructure(PlayerSummary.java:255) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.Surveyor.lambda$checkStructureExploration$4(Surveyor.java:73) ~[surveyor-0.6.11+1.20.jar:?]
at com.google.common.collect.AbstractMapBasedMultimap.lambda$forEach$2(AbstractMapBasedMultimap.java:1322) ~[guava-31.1-jre.jar:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at com.google.common.collect.AbstractMapBasedMultimap.lambda$forEach$3(AbstractMapBasedMultimap.java:1322) ~[guava-31.1-jre.jar:?]
at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
at com.google.common.collect.AbstractMapBasedMultimap.forEach(AbstractMapBasedMultimap.java:1321) ~[guava-31.1-jre.jar:?]
at com.google.common.collect.HashMultimap.forEach(HashMultimap.java:51) ~[guava-31.1-jre.jar:?]
at folk.sisby.surveyor.Surveyor.checkStructureExploration(Surveyor.java:66) ~[surveyor-0.6.11+1.20.jar:?]
at folk.sisby.surveyor.Surveyor.lambda$onInitialize$5(Surveyor.java:107) ~[surveyor-0.6.11+1.20.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
at net.minecraft.class_3218.handler$bhb000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:5240) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18765(class_3218.java:396) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
... 5 more
```

**Comment by Rage-GitHub** [comment]
This seems to have been fixed in the [0.6.11 update](https://modrinth.com/mod/surveyor/version/0.6.11+1.20) of Surveyor Map Framework.

**Comment by Rage-GitHub** [comment]
Reopening, as this seems to be present still even with latest Surveyor Map Framework update.

**Comment by Rage-GitHub** [comment]
Also posted this issue over on [Surveyor](https://github.com/sisby-folk/surveyor/issues/37).

**Comment by sleepingdragoninn** [comment]
closing this as the second crash already has a thread - bumped to 0.6.11 in atlas proper!
