### ISSUE TITLE
disconnect from server when killed by player with named item

### ISSUE THREAD

**Issue by Gamershy** [sleepingdragoninn/antique-atlas#229]
Any time I'm killed by another player on a fabric server (no other mods other than performance ones on said server), the game disconnects me with a network protocol error, but only if the item I'm killed with is renamed. This is, as you can imagine, immensely annoying.
```
[22:29:18] [Render thread/ERROR]: Failed to handle packet class_5892[playerId=1204018, message=translation{key='death.attack.player.item', args=[literal{Gamer_Shy}[style={clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell Gamer_Shy '},hoverEvent=class_8826[action=<action show_entity>, value=net.minecraft.class_2568$class_5248@d78fae18],insertion=Gamer_Shy}], literal{SymbioteMC}[style={clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell SymbioteMC '},hoverEvent=class_8826[action=<action show_entity>, value=net.minecraft.class_2568$class_5248@33317cad],insertion=SymbioteMC}], translation{key='chat.square_brackets', args=[empty[style={italic}, siblings=[literal{Sword of Shade}]]]}[style={color=aqua,hoverEvent=class_8826[action=<action show_item>, value=net.minecraft.class_2568$class_5249@f179ffc1]}]]}]
java.lang.IllegalStateException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
	at com.mojang.serialization.DataResult$Error.md5a3898$owo$lambda$addStackTraceToException$0$0(DataResult.java:565) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at folk.sisby.surveyor.util.TextUtil.stripInteraction(TextUtil.java:19) ~[surveyor-0.6.23+1.21.jar:?]
	at net.minecraft.class_634.handler$gfd000$surveyor$onDeathScreen(class_634.java:16541) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_34075(class_634.java:1598) ~[client-intermediary.jar:?]
	at net.minecraft.class_5892.method_34143(class_5892.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_5892.method_11054(class_5892.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
```
This is the error in question. The only modded bit in there is surveyor, it appears that the mod crashes the connection to the server due to the "cause" option for gravestones not properly being able to parse the custom death message. Again, any other death message works just fine, only if a custom item name is involved does the game disconnect.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/3f08421d-70ed-44ba-b397-24b08eb4ff46)

can't seem to reproduce. can you nail down an exact reproduction case with a clean instance? (which sides the mod is on, what mc version, no other mods, etc)

**Comment by sleepingdragoninn** [comment]
new surveyor hotfix .25 will prevent crashes with this, but do get back to me if this reproduces in isolation on .24 - the crash-safety path removes text formatting if it's tripped which is unideal.

**Comment by sleepingdragoninn** [comment]
ah wait i think this is documented in https://github.com/sisby-folk/surveyor/issues/49
