### ISSUE TITLE
Game crashes while loading world.

### ISSUE THREAD

**Issue by JosephRguez** [sleepingdragoninn/antique-atlas#258]
Forge load correctly all my mods, but when I try to load a world the game crashes with the message "The game crashed whilst exception in server tick loop
Error: java.lang.ArrayIndexOutOfBoundsException: Index 3421 out of bounds for length 3361"

 Here is the report:
---- Minecraft Crash Report ----

// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================

// Why did you do that?

Time: 2024-12-25 11:40:15
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index 3421 out of bounds for length 3361
	at folk.sisby.surveyor.util.RegistryPalette.find(RegistryPalette.java:32) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at folk.sisby.surveyor.util.RegistryPalette.findOrAdd(RegistryPalette.java:45) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at folk.sisby.surveyor.util.RegistryPalette.findOrAdd(RegistryPalette.java:50) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at folk.sisby.surveyor.terrain.RegionSummary.readNbt(RegionSummary.java:117) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at folk.sisby.surveyor.terrain.WorldTerrainSummary.lambda$load$4(WorldTerrainSummary.java:64) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at folk.sisby.surveyor.terrain.WorldTerrainSummary.load(WorldTerrainSummary.java:64) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:classloading}
	at folk.sisby.surveyor.WorldSummary.load(WorldSummary.java:28) ~[surveyor-0.6.25+1.20_mapped_srg_1.20.1.jar%23754!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.handler$zdb001$surveyor$loadSummary(ServerLevel.java:2148) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:surveyor.mixins.json:MixinServerWorld from mod surveyor,pl:mixin:APP:neruina.mixins.json:catchers.ServerWorldMixin from mod neruina,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor from mod aether,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:204) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:surveyor.mixins.json:MixinServerWorld from mod surveyor,pl:mixin:APP:neruina.mixins.json:catchers.ServerWorldMixin from mod neruina,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor from mod aether,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin from mod neruina,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin from mod neruina,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.essential.json:server.integrated.Mixin_FixDefaultOpPermissionLevel from mod (unknown),pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin from mod neruina,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23414!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin from mod neruina,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by sleepingdragoninn** [comment]
Rare palette crash found only on connector 1.20.1, haven't been able to reproduce it so far, and mysteriously disappears on its own

**Comment by sleepingdragoninn** [comment]
dupe of #208 - if your crash was singleplayer report so there.
