### ISSUE TITLE
2.0.0 - Crash with fasterrandom 3.0.3

### ISSUE THREAD

**Issue by k0nstruct** [sleepingdragoninn/antique-atlas#74]
**Probably all** versions of antique atlas introduce a startup crash when paired with fasterrandom (v3.0.3 -> v2.0.0, down to 1.6 it works.)
What was introduced in version 2.0.0 of fasterrandom probably breaks antique atlas. Mainly, fasterrandom claims to alter cave generation to optimize it. [modrinth page](https://modrinth.com/mod/faster-random)

The crash doesn't give any exit dialogue with Quit loader, but the logs mention this:

```
---- Crashed! ----
Date/Time: 2024/04/01 12:29:00.1482
Quilt Loader Version: 0.24.0

-- Crash --

java.lang.RuntimeException: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:459)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:254)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:167)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#faster-random:fasterrandom.mixins.json:RandomMixin from mod faster-random] from phase [DEFAULT] in config [#faster-random:fasterrandom.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454)
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: #faster-random:fasterrandom.mixins.json:RandomMixin from mod faster-random target net.minecraft.class_5819 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 11 more

```

**Comment by k0nstruct** [comment]
This conflict *Is not exclusive to v2.0.0* : recent changes are not the cause of this crash!

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/927c506d-2ade-4763-9764-28124e9a00b8)

can't reproduce, you'll need to bisect.

**Comment by k0nstruct** [comment]
After investigation I've found that this conflict only happens when:
Fasterrandom is installed
Antique atlas is installed

And a third mod: It happens when [VMP](https://modrinth.com/mod/vmp-fabric/versions) is installed
OR, when [Sounds](https://modrinth.com/mod/sound) is installed.
_Removing the two, it launches without problem. **But if one (or both) are present, this crash occurs**_ (and the log file I provided is all that's given to debug.) I'll investigate more and report it to the other authors.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/fca70faa-2f57-415a-ba41-80ce46b3b995)

can't reproduce again

**Comment by k0nstruct** [comment]
Okay what
Is this just a quilt issue maybe? Or some corrupted files on my PC? Don't bother with this, I'll come back when I find the real problem, sorry for the disturbance. Maybe close temporarily even.

**Comment by k0nstruct** [comment]
I'll close this until I can pinpoint what's happening.
